### ISSUE TITLE
it may lead to "cross-tenant contamination" issues?

### ISSUE THREAD

**Issue by shiqw** [CodEaisy/TinySaas#7]
services.AddSingleton<ITenant>(provider => provider
             .GetRequiredService<IHttpContextAccessor>()
             .HttpContext
             .GetCurrentTenant<TTenant>());
         services.AddSingleton(provider => (TTenant) provider.GetRequiredService<ITenant>());

         var tenantBuilder = new TenantBuilder<TTenant>(services);
         tenantBuilder.WithStore<TTenantStore>();
         tenantBuilder.WithResolutionStrategy<TResolutionStrategy>();
         return services;

In the code snippet you provided, the ITenant and TTenant are registered with a Singleton lifecycle. This approach needs to be handled with care in multi-tenant applications, as it may lead to "cross-tenant contamination" issues, where different users or requests accidentally share the same tenant information.

**Comment by codeprefect** [comment]
@shiqw, It will still be a singleton, but I need to move the logic of retrieving the `TTenant` instance further down in the system.

Thank you.

**Comment by shiqw** [comment]
你好！你的邮件我已收到
